# This project follows the Ribose OSS style guide.
# https://github.com/riboseinc/oss-guides
# All project-specific additions and overrides should be specified in this file.

AllCops:
  TargetRubyVersion: 3.0
  Rails:
    Enabled: false
  Layout:
    IndentationWidth: 2
    LineLength: 80
  Style/FrozenStringLiteralComment:
    Enabled: false
  Metrics:
    MethodLength:
      Max: 50
    ClassLength:
      Max: 300
    BlockLength:
      Max: 50
